module.exports = [
  "By npm's best estimates, 50% of users started using node less",
      "You'll never get me to say ES2016",
      "did i win the net award",
      "New browser security features like Subresource Integrity are making the web a safer They don't do much good",
      "JS, it's not because I don't care, it's because no one taught me",
      "ain’t the web doomed these days",
      "i literally don't care if you don't like javascript",
      "your entire DOM it's okay if that makes you nauseated, it does me too",
      "JavaScript, rather than This increases the speed",
      "Fun Fact: Web Workers are, in fact, very",
      "still riding high on JavaScript enthusiasm, and yet keeping strong",
      "in it seems increasingly crazy",
      "ember",
      "type checking has been",
      "what IS computing?",
      "looks like \"normal JavaScript\" to me",
      "I'm going to create a $VXX for NodeSource",
      "Real programmers spend their day fighting",
      "you need to know about",
      "So, do people actually test their JavaScript, or",
      "Speaking as a JavaScript conceptualizer,",
      "honestly javascript",
      "Just kidding about TypeScript",
      "component code in Remove that",
      "one must use the shady DOM APIs",
      "this has taken too long I've lost interest in helping Will move on to another framework",
      "your favorite MVC framework might make a comeback",
      "your silly reimplementations",
      "was kinda right about Turbolinks",
      "clojurescript isn't crazy",
      "and the Node Foundation? TL;DR We expect to continue",
      "Any plans for react-router to support React",
      "omg",
      "the DOM!",
      "I'm looking for a hacker who knows",
      "is wrong with Bower",
      "i got in a fight with some unit tests but i won",
      "npm protip: embrace the futility",
      "one last call for JSConf One final time to remember all of the great times, all of the special moments, all of the family",
      "The day has come where I have seen being used",
      "Babel, plz",
      "of course, JavaScript was created long before Node, but Node introduced the language",
      "expect the adoption of v4 to be It will take",
      "turns out OOP actually has its place who knew",
      " can't you count?",
      "when your JavaScript objects get mutated",
      "I just realized I can SSH into my living room",
      "can anyone familiar with v8 help me understand",
      "i don't want to learn CSS! you can't make me!",
      "the Platform Also Adds Marketing",
      "hay now!",
      "but I dont want to pull babel in for every script",
      "Aww, look, HN is offering up ideas",
      "the web, not the app ahhhhhhhh",
      "Safari DM me",
      "java script\" I yell, forking the repo",
      "the libraries you use are jerkbutts",
      "disturbing, how JSX has become supported",
      "code is the best I can feel the debt",
      "to solve a real Keep exploring, coder babes",
      "floating around available for if you're into that kind of thing",
      "just spend an inordinate amount of time each day thinking of javascript",
      "God, turns into something",
      "gulp sucks currently",
      "Yes, I run my server code through",
      "dynamic Is that actually a good idea",
      "that Shadow Dom",
      "Sprinkle that HN fairy dust on ya and that UglifyJS",
      "Broccoli is actually being used",
      "with wombats omg I can't even",
      "<% %> Execute arbitrary inline JavaScript This is useful",
      "If you're doing development and you can't use Promises,",
      "for I'm sure there are already angry gods circling overhead, drawn by my",
      "no semi-colons is basically impossible for me",
      "converted my React app to ES6 I think",
      "write a Wikipedia article about me",
      "is used at all companies",
      "hoo, the es6 spec",
      "React code I laugh at",
      "blah blah something css joke something blah",
      "support syntax highlighting? this is ridiculous",
      "ES2016 QUESTION:",
      "Am I the only one who uses \"grep",
      "got fired for quoting",
      "2015 Node community adopting literally everything",
      "javascript that often smells",
      "De Morgan’s Law doesn’t necessarily work",
      "The render loop loops forever, waiting",
      "Backbone – Backbone isn’t that “smart”, so",
      "Tired of guessing what versions of Ember work",
      "possibly in the future, Microsoft Edge will run in Firefox with few changes",
      "CSS is an invention of the devil - worse",
      "Browsers *could *stop",
      "Please do not contact me directly about",
      "a simple JScript that uses HTML5",
      "use ember tom",
      "~ being a web developer / designer is a thing that i love ~ so fuck the haters",
      "Adopts Universal JavaScript, Drops Java",
      "chase the JS framework dragon",
      "I'm retiring from posting tweet-sized JS snippets",
      "Does ES6 have any special sauce",
      "we can make a javascript-heavy web",
      "Unfortunately, due to Selenium",
      "all aboard the ES6 hype train",
      "people like to give JS devs grief",
      "Browsers don’t actually know what pixels are",
      "Who needs web performance when your web page loads",
      "I'm not familiar with what you do or have done, but have you ever tried to make a website back in the day? Ever tried to support IE6? 7? 8?",
      "I believe that the answer as to why JS keeps growing is largely design by course I’m I implemented my own JavaScript",
      "take a when you wake up, don't tweet at write some contribute be you'll be fine",
      "so I switched to",
      "I still don't know what JavaScript is",
      "we'd like to thank the community for making it the garbage",
      "Why didn't all JS Framework creators combine into one team to create only one true JS Framework ?",
      "taken to calling Ember a \"garbage collection\"",
      "JSDoc Right? Right?",
      "As a counterpoint: is your JS webapp really",
      "JavaScript, tell your story",
      "technologies, which combine to create a comprehensive framework for building complex JavaScript",
      "lol at github",
      "Hot JS tip: do not work for companies that recommend you read",
      "I just wanna write JS, wtf",
      "I should write about the web I still have thoughts about",
      "JavaScript is still the only language guaranteed",
      "Good luck with your adventure with modern JavaScript!",
      "I trolled npm",
      "i'm a nerd, years ago i fucked with the javascript",
      "it would be a great start to understand JavaScript",
      "securing the web -- maybe",
      "What are you not getting about this?",
      "i think working in front-end has spoiled me",
      "I *don't* write code but have been to a million js meetups",
      "dropping in on the first ever",
      "shame that es6 can't",
      "I HAVE A PAGE ON WIKIPEDIA?!",
      "Not trying to be rude, just",
      "Didn’t mean to sound like an",
      "I haven't been to a web/dev meetup where I didn't feel",
      "me? I have a degree in computer What are you not getting about this?",
      "Breaking the Web With CSS",
      "There's too much material out there talking about \"ES7\"",
      "Is there a German word for the feeling of despair at the idea of npm",
      "one guilty es7 pleasure i allow myself",
      "Nobody uses web components",
      "Safari (weird)",
      "following best It is a great help when you want to maintain high code It can also be annoying",
      "javascript bots are the worst am i right? AM I RIGHT? JAVASCRIPT BOTS??",
      "Get out of your JavaScript ivory towers and think",
      "no need for all the \"Cool\" methods you employ to create what you consider to be a web site",
      "the web's not entirely short of bonkers",
      "I would paraphrase as follows: If you want to show off how clever you are",
      "How to componentize?",
      "real world code, not just",
      "benchmarks don't reflect perf in any framework ime",
      "Ever been in an argument where someone said \"thats not true\" and you say \"uh, JavaScript would evaluate it as truthy\" and you lose",
      "ClojureScript ClojureScript can compile",
      "one day the Web will be perfect and complete and I will not need",
      "code is nearly always too much",
      "JavaScript has historically results remain to be",
      "the web itself is built by all of us, day to day—that, to me, is moving the open web forward",
      "didn’t go far enough",
      "advance the Too much",
      "Don't",
      "Don't listen to me about code",
      "I’m not talking about the experience of the website, but of the website",
      "Web developers MUST NOT (in the sense of RFC 2119) use HTML 5",
      "With the help of Arrow Functions it is possible",
      "just stop doing back-end development completely",
      "Disagree with",
      "4 levels of abstraction to avoid",
      "the JavaScript Valley warned the citizens, but",
      "I expect JavaScript to be forked",
      "Write ES5 and time how long it takes you",
      "with css, my hat is off to people that manage to actually make things",
      "Tune in for the finale of Real World: JavaScript",
      "if you're into, like, array buffer stuff",
      "jenn schiffer's serious",
      "Full-Stack immutability",
      "JavaScript, and they totally rocked it",
      "got fired for quoting",
      "Client-Side JavaScript",
      "i want to show you the",
      "I'm okay with using pretty good",
      "still waiting for my public apology from",
      "Markdown syntax questions? aren't you wearing",
      "I’d like to say that in general I thoroughly approve of the HTML5",
      "Is Polymer used",
      "Sorry folks - fonts are broken",
      "return foo(), bar();: really",
      "like a horsefight situation",
      "fight me irl over this semicolon biz",
      "be old Safari instead of modern Safari",
      "Probably everyone in JavaScript shouting",
      "CAN I HAZ async",
      "in my React apps all I've done is create horribly leaky abstractions",
      ";;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;",
      "The other day I came across this tweet from Kyle Simpson: I don’t have a term for Kyle, but",
      "If you use semicolons in JS, try spending a month writing TWO semicolons at the end of each Then you'll know",
      "defend JS to a fault",
      "defend JS to a fault",
      "Interesting idea: I don't use JSX",
      "It'd be great if every library/framework was broken",
      "50 JS twitter bots for mentioning Angular",
      "Front end development is hard because",
      "I wish i was slinging JavaScript!",
      "framework, you aren't convincing me",
      "just don't software",
      "provides the foundation for enterprise-grade Node operations and",
      "React exposes everything it's awful",
      "I already know Backbone, Ember’s gotta sell me",
      "TYPEOF IS NOT SAFE Okay, I stole this",
      "“yandex” seems more like a mkting deal",
      "javascript was my own… it is literally a",
      "This is what’s wrong with the Web Platform: It’s 2015",
      "Flash is being resurrected by Famous and they intend for it to live Did you know that? I I wasn’t even aware",
      "Is this satire? I can't tell",
      "just stealing other people's quotes",
      "with the ever-growing JavaScript language, we’re continually working to improve",
      "could you people stop saying",
      "now Angular, Angular is in last place to me",
      "i swear i better not see you using ES7",
      "What's the worst that could happen? Seriously folks, jsx",
      "do it right and you don't need defense in depth",
      "im horse",
      "Ruby is defined by terrible",
      "\"oh \"wait, maybe this is a bad eh, whatever",
      "I am fighting with",
      "AT LEAST five npm modules",
      "are there any benefits to using Angular over Ember, ever?",
      "Makes me really sad",
      "?",
      "my 1 step solution for javascript happiness:",
      "Javascript is a breeze",
      "pronounced \"Bae-bull\", not “babble\"",
      "strawberry javascript sounds",
      "the madness of the Javascript",
      "Problem: Grunt Solution: Gulp Problem: Gulp",
      "Do you use this in production? No, but we have every intention to",
      "Just Enough jQuery To Get By",
      "Let’s do away with modules",
      "currently 10X",
      "i wish would stop",
      "That's weird magic-at-a-distance that I personally think we should try",
      "with love: Get well soon Laura!!!!",
      "React is slower than vanilla",
      "alert('🐴')",
      "there is nothing that cannot be made to work in ECMAScript edition 3",
      "small DOMs",
      "just use \"THE DOM\"",
      "Mozilla isn’t yet sure what technologies to adopt",
      "You Can’t Spell CSS",
      "managing styles entirely in JavaScript? I love I'm all CSS is",
      "I am trying to help And I'm telling you isn't doing anything",
      "it might have been the wind, but I thought I heard \"Rust\" whispered by someone",
      "The plan calls for one",
      "IE my",
      "There is bug and",
      "NodeJS is magically faster",
      "write everything in JavaScript It’s time",
      "Hundreds of devs reach out to remind me I'm to blame for their JS",
      "for a slow Dom",
      "Hell yes, JS",
      "there's a sea of JS",
      "React is slow",
      "Does the React team even care?",
      "Moving to HTML5 Premium",
      "see give his first ever talk",
      "I have another concept that is of the happiness I feel when I'm reading of the Web Assembly work",
      "jsconf was so strange, lol!",
      "I accidentally did `npm publish`",
      "years Before",
      "ember sux lol",
      "Sure, any large code base needs to be modular, but why",
      "javascript don't crash",
      "or",
      "thought leader like",
      "i'm using browserify wrong, look",
      "\"Is math important?\" - great What is \"math\"?",
      "You broke",
      "everyone can pick their own Flux let’s fix this",
      "Node & Express apps forever, no matter what",
      "threw a wombat",
      "Playing around with React a little Gagging a little",
      "modern JS! Holy crap",
      "I love JQuery, there's a significant number of JavaScript programmers who do",
      "web developers is basically a nightmare of mine come true",
      "pin the semi-colon on the donkey()",
      "blinky light things & JS",
      "TypeError: Cannot call method 'find' of undefined D’oh!",
      "HOT JS News",
      "Very important! Brendan Eich does something",
      "celebrate the procedural side of JavaScript",
      "JavaScript means you can pop the collar",
      "UI framework, show me a pretty",
      "why not always compile JavaScript to WebAssembly?",
      "I see you at",
      "Te gusta Javascript?",
      "If you have a style of working that makes you productive, I don’t really care",
      "I’m not *against* RoR… I just",
      "I don't think many web developers really care that much",
      "I hope you're coming to to hang out with me and",
      "the job of You might learn it by You might ask a You might get that information out of a book, or a website",
      "the problem is that bullshit mobile safari",
      "live reloading?",
      "you’re doing Node wrong",
      "JS over the same timespan will endure and evolve to absorb",
      "deconstruct the functionality",
      "One day you’ll download a JavaScript",
      "Maybe I like JS too much",
      "thing is, ES6 brought in many things that took years",
      "you might not recognize JavaScript It's pretty",
      "I'm not talking Babel or any other tools like that, I'm talking straight up",
      "your JS codebase, I'm sure it would happily compile to Wasm",
      "showed up to BrooklynJS but forgot to bring my internet cred",
      "what prevents me from criticising JSX from the outside is that I've yet to encounter anyone that's used it",
      "I'm pretty excited about",
      "If you want a vision of the future, imagine javascript",
      "ECMAScript is based on several originating technologies, the most well-known being JavaScript",
      "If I can do it with javascript and I´m on my way!",
      "it is not too late will save us",
      "Just adding my two Wanna be a good JS dev? Go play around",
      "i'm a proud +1'er",
      "We'll",
      "never",
      "Syntax is",
      "Wow fuck I'm going to pretend this Lua file is JavaScript",
      "he's learned from reading jQuery's source code, not sure exactly how",
      "i put one semicolon before and one after",
      "There really is only one ASI rule you need to remember [0] in practice: don't",
      "Wish the Safari team collaborated more",
      "jQuery without the jQuery",
      "Node's event driven design is also called \"co-operative multi-threading\", and is more efficient than OS threading",
      "It's got it It's not California Style theyets",
      "JavaScript build systems and",
      "we may have hit 'peak Node'",
      "I also started by saying “to be more I do not think your current definition is wrong, just that it should be broader and more com",
      "full re-renders can be made While we did not",
      "Would someone in the community be willing to make an Ember Data",
      "the same thing with Symbol could be accomplitheyd with a simple UUID generator",
      "What Javascript needs is a way to",
      "JS, I just get sad",
      "The reality of javascript is different",
      "what ever happened to",
      "Why has this taken so long? To cut a long story short, vendors",
      "Ember, why did I neglect you for so long? Please take me back",
      "turns out, ES2015 name is **always** used as a joke",
      "That REST thing can be over-rated",
      "Anyway, Hi <3 <3 <3",
      "the measure of success for a JavaScript framework is popularity",
      "write Javascript in a tree",
      "automatically get scalability for free with node",
      "the You may be surprised",
      "how truly futile it is to stand in the way of JS",
      "Why do CSS purists argue",
      "I can report that is having a heart",
      "flux: never",
      "goto for ClojureScript",
      "JavaScript Force",
      "a single javascript file that contains every ECMA-262",
      "Another brilliant decision in React",
      "web frontend scene is witness",
      "Some folks want a unified language of the web instead of CSS, HTML, and increasingly looking like JS",
      "once called me 'a hero'",
      "Me, I think HTML",
      "my fave part of github is needing",
      "You don't even need to use React, that's what is so great",
      "just passed on",
      "don't use isomorphic javascript",
      "semicolon happy, adding one at the end of EVERY SINGLE",
      "I wish the v8 team wouldn't remove stuff",
      "Yes, all",
      "Somehow, I’m just not all that worried about “the web",
      "consider that some people literally can't run your JavaScript without melting",
      "mnfcidlnbnupuntvdmdmasbsriiebabolalocac",
      "🔥Protip: Use CSS :not()",
      "make light blinks with node",
      "ok, who sent me the anonymous box full of Mozilla",
      "i work at google on node’s",
      "Is React a framework?",
      "represent turbolinks?",
      "The nightmare scenario for TC39 is basically someone at a popular website",
      "I run the",
      "Advanced mistake not knowing",
      "Hey is it too late to fix ES6",
      "javascript joke *is* funny",
      "yes I am aware dojo already did that",
      "start with Is var really necessary",
      "becoming comfortable with JavaScript is probably harder than learning JavaScript in the first place",
      "heard rumors about Ember and React",
      "makes me wonder why I was trying to be Fancy and use Ember",
      "can’t believe i made it through another without getting caught",
      "fly home from",
      "anything related to JavaScript and it’ll sound interesting and amazing",
      "this is me",
      "Bad abstractions are real",
      "Javascript WILL BE",
      "ya dingus",
      "ya dingus",
      "Yes they is a coder That is why they is at a conference for programmers",
      "JavaScript in, JavaScript Hopefully",
      "you want really good  So what",
      "components are an anti-pattern in",
      "Hey come karaoke with Right now",
      "never read the fucking manual",
      "CSS is kinda broke huh?",
      "Hey I’ll be doing poolside track in an shirt",
      "So, internets, somebody wrote a JS framework",
      "now to emerge for the pool track",
      "Wait, What is Cloud9 Again?",
      "Google Chrome devs know my opinion, hopefully",
      "NaNs ALL DAY",
      "(silence)  (continued silence)  (silence continues)  (silence intensifies)",
      "(grinding noises)",
      "i'd write a p good textbook i think",
      "best JS  If I want to",
      "Through out history, JS has been",
      "non-JS ;) I wish somebody would replace it",
      "if you lick a 9-volt battery, you'll erupt in flames",
      "It's not hard to be faster than React",
      "making the web i am sorry",
      "Come find me",
      "I'm In the bar, hacking",
      "yayyyy so empty",
      "WHOOOOOAAAA!!!!",
      "involved in the JavaScript Is that weird?",
      "What were you using before",
      "\"isomorphic\" javascript isn't meant to be a joke",
      "V8! V8! V8!",
      "Every time I wake up it seems like there is a new version of",
      "What we can learn in web development from other technology/disciplines \"You're doing it wrong\"",
      "\"Always bet on JS\" is short for \"There have been dozens of challengers to JavaScript over the last 20 years, and they have all failed",
      "I'm secretly an 11 year old",
      "except for Ruby",
      "write every other language in JavaScript",
      "feels fast as hell with JavaScript",
      "So you want to add goto to JavaScript",
      "sexton!",
      "have attended every single neener neener",
      "Wow, Wow, wow,",
      "omg, I'm declaring JS essentially bitcoin",
      "I think everyone who writes JavaScript needs to read",
      "about to be so angry about JavaScript",
      "Multithreading and asynchronous callbacks are the same",
      "js is more usable out of the box",
      "Is \"important software\"? I guess",
      "+1 👍 totally agree",
      "I have no idea what you're talking",
      "Those milliseconds can really add up",
      "seriously, name it \"UnderDash\"",
      "The web dev community has a surprising and interesting culture",
      "we might start seeing things like this (substitute your favourite language): java` class HelloWorldApp { public static void main",
      "i'm not really a fan of any object-orientation",
      "the web is basically The Worst",
      "I’ve never really understood what “homoiconic” is supposed to mean",
      "with DevTools open JS runs about 100 to 1000x faster",
      "AFAICT, JS parsing == fucked",
      "jQuery makes it into the repository, it’s a virtual certainty",
      "I learned JavaScript because I'd promised to",
      "emceeing jsconf next week!",
      "inclined to be severely prejudiced against anything that mentions \"isomorphic\"",
      "You probably heard of the Ember",
      "systematically every JS dev",
      "i put markup in my JS and not regretted it",
      "Java (the script)",
      "For the record, JSX wasn't designed",
      "the people, not the the code doesn't matter",
      "enough thoughtleadering",
      "DOM is free; you can write as much as you want",
      "The solution is simple: ditch the All of",
      "I JS is beautiful in the parts",
      "I still don't understand these \"too many frameworks\"",
      "do you guys happen to have a high quality version of the Glimmer",
      "Anything NaCl can do, can do too",
      "is `var` really dead? Have you replaced it",
      "[tl;dr] You can easily replace jQuery",
      "CALLBACKS ARE BETTER THAN SAY IT",
      "Can you please tell me a story about a JavaScript",
      "\"Can you explain how 'this' in JavaScript works?\" Of",
      "My biggest gripe would actually be I mean,",
      "millennial JS dads would understand",
      "use Mocha and  Did you like this answer?",
      "ES2016 is merely a year away!",
      "today I discovered What a journey! I've grown a TON",
      "Should I be ditching node for io?",
      "congratulations, you have probably just experienced JavaScript",
      "I never liked",
      "We’re still using YUI",
      "For a single test case where V8 goes off the rails there are millions of lines of code across the globe",
      "You should never \"optimize\" JavaScript code",
      "/* sound of silence */",
      "in you can probably take advantage of the way exceptions are handled",
      "ES6 is packed with weird but well-defined",
      "\"the whole App is written in think it's perfectly fine",
      "Caching the array length still gives you a small speed boost",
      "node is surprisingly complicated",
      "the slowest, excluding Ember",
      "i'm not sure this is going to work out",
      "React performs 2X slower",
      "kind of Of course it",
      "where tools are",
      "There’s this joke about a new javascript library",
      "a bit more Lisp-y if you will",
      "Will take engines a",
      "you could use Bower for Erlang package management",
      "no arrays no functions",
      "Angular 2 They are They describe",
      "don't use `delete` keyword, since I know it might create a node that GC's can't clear",
      "tweeting about",
      "not every JavaScript programmer",
      "\"tweeting at it's effective",
      "async? promises?",
      "it's just about code, no politics here",
      "ECMAScript has evolved through considered discussion and debate",
      "salute to John Resig, an American software engineer, entrepreneur, and creator of the jQuery JavaScript",
      "From my POV, React does a lot of stuff",
      ";___; Oh well,",
      "with JS, I might as well just use JS",
      "The more I write and talk about code, the less I care",
      "WTF CSS‽",
      "What's in Uh, queries?",
      "yaaaaaaaaaaaaaaay Where's at?",
      "something something douglas crockford",
      "like Om and Reagent, but without the opinionated",
      "why aren't you using react",
      "you are an important GitHub user",
      "be the worst javascript framework I've ever seen",
      "It can be tricky to write software that produces the correct But we all know that",
      "The team has done more in a few months than Joyent did in 2 personally, don't care",
      "WHAT DOES OPTIMIZATIONS” MEAN",
      "write JavaScript that obviously makes you an ideal candidate",
      "I have just one simple rule for semi-colon:",
      "all to build jquery!",
      "node is making me v sad",
      "it's still just too hard to write JavaScript that works",
      "If you’re managing state correctly, then you don’t even need to",
      "javascript so ¯\_(ツ)_/¯",
      "array/obj Why don't you put those in a separate file?",
      "apples?",
      "ARM is a tricky beast",
      "Everyone blames JS",
      "imagine a version of jQuery that doesn’t even",
      "a book about making JS apps that work",
      "npm and I really did not want to do",
      "Argh, bower is Almost but not quite",
      "Glimmer? Oh",
      "As a JavaScript developer, I’m sure you’ve already been falling into this scenario: something goes wrong",
      "in just 10 days",
      "get defensive when people slag off on JavaScript",
      "You don't have to use Just never",
      "why this thing exists?",
      "Want to break the stranglehold that Dart has on Google",
      "people tend to market JS these days",
      "thoughtlead the shit",
      "the best name for a loop variable is \"swag\"",
      "Is Ember fast yet? NO",
      "This whole ES6 thing is moving pretty fast, huh?",
      "i get it, you ~*love javascript*~",
      "THE",
      "JavaScript becomes the next systems programming language",
      "es6 js makes me sad 🙈",
      "SPACE with JavaScript 🚀",
      "FOAM has an unfortunate terminology",
      "I occasionaly read the esdiscuss list, and from those discussions, I get a sense that it is incredibly difficult",
      "people here are gonna say",
      "It's apparent that likes to build sand castles",
      "javascript make me literally foam at the mouth",
      "mad about your javascript",
      "deeply MVC",
      "what is up with these urls?",
      "Raise your hand if you’re thinking about JS",
      "JS party!",
      "The story gets even worse if you are writing Coffeescript",
      "*writes a build system for javascript*",
      "V8's unstable",
      "I always thought was a robot",
      "Preorder Now for Lifetime Access to all my JavaScript",
      "Anyway, whatever, the web is a mess, we all know",
      "Not convinced you *can't* write a decent client side app",
      "the guy complaining about Shadow DOM",
      "Survivors of the Browser Wars lived only to face a new The committee which controlled JS—TC39",
      "it's inevitable,\" says \"It's the way",
      "OSS is when tons of people use and appreciate your worst",
      "good Web performance is easy to reach with zero dependencies, totally cross browser, and using just the good old DOM",
      "Promises never used them",
      "Hey are you attending this year's you cool",
      "i·so·mor·phic",
      "I do not enjoy Turbolinks but how could I",
      "if you're thinking about putting a 9/10 for Javascript and you don't know what a closure is",
      "built on top of Angular :-(",
      "browser sentry chickens",
      "Figured it out Deleted node_modules and npm",
      "returned Ignore",
      "turbolinks is fundamentally not an appropriate tool",
      "not every JSON API",
      "not every JSON API",
      "You Might Not Know About jQuery",
      "JS spec is wrong",
      "the That part",
      "i'd say 99% of the time i don't end up needing the view layer",
      "I think I can state that I’m one of the world’s leading experts",
      "goddamnit, goddamnit",
      "HA!",
      "I am so thankful for all the people in the OSS js world who help to keep making it goodSnark",
      "ignore any advice people give you about micro-optimising javascript",
      "If you're getting into don't",
      "call it “Dojo 2”",
      "serviceworker q: Is it possible",
      "If you find yourself saying \"Ember Data doesn't support X\", there's a pretty good chance",
      "is a goofy *compile* target",
      "Somewhere, in a Utopian future, people don't bundle",
      "The prevailing ‘wisdom’ in popular JavaScript (this week)",
      "- it infects",
      "Wrap everything in a try/catch? Um – ;)",
      "CSS is for the",
      "quite literally no tooling for ClojureScript",
      "Can I use this with <my favorite framework>? Maybe! It won’t help too much",
      "gazongabytes of javascript trying to deal",
      "joining the npm board",
      "sweet, you can debug IE11",
      "JS endures",
      "team has seen the good, the bad, and the ugly of Here’s what we’ve",
      "language-wise, TypeScript seems much more interesting than Go",
      "do without npm, it's just much easier",
      "How are people distinguishing between npm packages",
      "As usual, Dates in JavaScript",
      "the time-honored tradition of taking yet another noun and making file out of it",
      "JavaScript as battlefield",
      "forget ES6 transpilers",
      "it's fantastic and amazing that everybody has to use JS independent of their preference",
      "After nearly 4 years of work - the first ClojureScript release that genuinely feels good",
      "no matter what you do, there is always something funky in your JavaScript code, I would bet",
      "data binding, jeez GET WITH IT",
      "standards is so 2011",
      "the error in the browser is that mobile can't",
      "What is this thing called AtScript I’ve heard of?",
      "Before we go further, I would recommend having a knowledge of EcmaScript",
      "when you use small packages to solve small problems, you get much less",
      "Enterprise JavaScript, though, does have For one,",
      "Pls",
      "mongodb?",
      "Yeah, statically determinable stuff would be awesome, we should be doing that",
      "fast enough J A V A S C R I P T",
      "hello lol :)",
      "async There's rope there to hang yourself",
      "two way databinding! WEAK",
      "async/await is pretty cool, so I hope someone looks into it",
      "you shall not call it",
      "\"caused an error\" is not enough detail for a bug report?",
      "you unlucky souls that have to deal with JavaScript build tools",
      "I have seen some Javascript in my been getting paid",
      "the original jQuery It’s really quite Thankfully this is something that was improved upon over time!",
      "unnecessary This… unfortunate… style preference",
      "The package ember-cli does not satisfy",
      "ES3 sugar? Not so",
      "JS being JS 😞",
      "Why TypeScript? Why",
      "front end frameworks I want my money back",
      "TLS implementation in",
      "JavaScript is a rather complicated practice, so",
      "There's only one thread in and it will get to your event when it's good and ready",
      "EDIT: I'm not advocating Ember",
      "Does it make sense to learn Angular",
      "the HTML that you write and the HTML you inspect",
      "open source is letting people down that you’ve never met",
      "undefined behaviour? I like",
      "JavaScript… but why? How exactly",
      "Ember is \"dead\"",
      "wanna join the hive-mind",
      "choose something other than do it",
      "if you support IE8 and use Ember, please leave",
      "say ES6 when you mean ES2015",
      "use a few",
      "I'd likely to formally submit my name as head of TC39",
      "React? I can certainly feel that there are reasons but I can't make them concrete off the top of my",
      "olden-days JavaScript",
      "does anyone have Spartan installed? what",
      "While writing specs, I often yearn for some kind of \"biketheydding",
      "Java JavaScript and Javascript JavaScript",
      "There are a few solutions out there, but none of them have the right",
      "performance, complexity, and It shouldn't be so hard",
      "could have been (could be?) a great official rendering engine for",
      "man, how did people stand to do ruby",
      "attribute to JavaScript that which can be explained",
      "thinking ahead to HTML6",
      "Typescript has optical types What are optical types? I've never heard of this",
      "only my and programming jokes are funny",
      "Good lord, it's JavaScript on the server, not royal palace",
      "work on JS then 99% of people on Earth are excited",
      "Forget about IRC, your only helping nerds",
      "thats not true, mdn",
      "ClojureScript has been pretty ass-backwards",
      "browsers? A: nobody's written a spec yet",
      "project idea: write an app",
      "MDN is useless and W3Schools has the information you're looking for",
      "I honestly don't understand what spurred the idea of migrating to ES6",
      "\o/ now supports HTML",
      "JS is hard even when you control the dominant browser / engine / platform",
      "The best technical advice I can give is: don't",
      "thank you to those of you who follow me despite mainly coding in JavaScript",
      "an efficient JS is a not trivial",
      "on compiling Dart to We have decided not to",
      "JS frameworks seem to exist just to make programming",
      "when we talk about JavaScript Promises",
      "I'm really glad Javascript is taking Mostly",
      "I'm about 4 weeks into Ember and very close to calling it quits and moving to I'll start from the say I'm an expert",
      "What the hey! Eich!",
      "Style rule: “no semicolons” Next",
      "There is nothing sad about React PATENTS",
      "Do you need to be an ES6/ES2015 expert? Probably not",
      "re-solving everything JS has solved already",
      "Don't be filing bugs in your code against",
      "I won't lie, I am getting frustrated with Web Developers who don't believe",
      "I suppose I could look through the Chromium source but I'm probably not actually",
      "most popular websites have Java code running in them -- Java that was translated into JavaScript",
      "HTML is a _markup language_, it's ridiculous",
      "anything you can do in Ember, you can do in Angular",
      "I stopped using document ready when I realized I could just place my <script>s right",
      "demand copious JavaScript",
      "finally showed up to",
      "your program cannot be correct except by accident",
      "Wanna give a special shout-out to Angular for making it impossible",
      "I was So I started looking at other JavaScript",
      "frameworks the",
      "99% of web devs probably don't even",
      "cant spell node without no and no",
      "coming for",
      "I really (still) don't get how people are developing client side JS",
      "Until ES7 arrives…",
      "Oh IE",
      "can we collectively stop writing about JS",
      "\"then\" never returns anything interesting",
      "HTML as if thats how we should be surfing the web now",
      "I don't know of any TC39 member who thinks it's \"good enough\"",
      "code that isn’t Who knew?",
      "gonna give a hard time",
      "Internet Explorer gets everything right Yes, there you What can i say…",
      "use virtual DOM or something to something",
      "Classes To be quite honest, I wasn’t aware of the good",
      "less Java and more JavaScript",
      "by all means load any kind of arbitrary JavaScript",
      "Nobody turns off",
      "We replaced it with JS and saw better perf/flexibility",
      "use the terms \"virtual DOM\" and \"shadow DOM\" interchangeably",
      "Firefox now has useful information",
      "what this site needs is some really well-written bad JavaScript",
      "Remember kids, if it's not HTML, it is literally impossible",
      "this JS thing, it's growing",
      "SIMD -- making JavaScript crazy",
      "next project: write a browser",
      "I un-muted some ember folks, lets see how this goes",
      "when you run npm install, you have everything you need",
      "I made a site for",
      "Blink has a new memory team, to ensure that memory is used",
      "I have the feeling that a lot of my tweets are inscrutable because I leave context out",
      "while talk is cheap, multiple independent language engines in one browser certainly are not",
      "Friendly reminder in JS =1 is not the same",
      "92% of CSS is touched",
      "clever also a philosophy",
      "server If that's your thing",
      "Yup, just one single file written in",
      "How many times have you been using a js app and thought \"wow this DOM is slow?\" You",
      "You probably heard something like how React is awesome",
      "just you don't really need Backbone",
      "code is very simple and low-level, and as a result easy",
      "heaps of JS, I love each & every one",
      "get \"you \"you \"then all you do out",
      "reactjs, slide up into my DMs",
      "I want to be excited by clojure script but I have failed",
      "you could write another JS framework!",
      "is now the only mainstream JS framework",
      "I'm not sure Lua is that different than Javascript",
      "i know JavaScript and don't want to learn anything else",
      "get a browser that supports canvas!",
      "don't break the web, or you lose",
      "Now that JS is respectable, consider this my standing offer to serve on anyone's PhD committee",
      "From the looks of Glimmer, Ember will no longer have perf",
      "open source: surprise users!",
      "imagine there will be a",
      "the temporal dead zone means that you can’t even",
      "know that JavaScript is async and async is Good",
      "because honestly, not everyone uses semver properly & I’d rather not",
      "is semver actually \"rules\"",
      "I'm not familiar with Ember, but why not just",
      "doing ECMA5 hacks",
      "JIT bugs :D",
      "JS 4 eva",
      "Do you run a JS meetup or conf in the US? Wanna maybe",
      "Glimmer, FastBoot, blah blah I'm still tripping y'all",
      "Believe it or not, TXJS",
      "Yehuda is a fully-costumed Tomster",
      "Wow, right? Just what you’ve been waiting for all these long",
      "I Read All the W3C Specs",
      "I Read All the W3C Specs",
      "the last JavaScript framework",
      "JS feels with your JS pals",
      "creating your own JavaScript framework out of a microframework and a DOM library is madness, maybe",
      "IMO, \"Framework fatigue\" is caused mostly by authors",
      "A JS framework on every table: why",
      "I think React has It's at about the same stage of maturity that Angular was five years ago",
      "deep into an Angular application and can't move",
      "the Internet's finest JavaScript thought lords",
      "my conference talks are always 10 hours long",
      "you might want to avoid due to problems",
      "The only large question I see here is what would happen",
      "looking unsuccessfully for the ES6 answer",
      "Anyone know the fastest way, in JS, of creating",
      "Note that as of our release, jsdom no longer works",
      "javascript! :) i declare you the",
      "1-2-3-4, I declare a browser war!",
      "Remaining Tasks: Don't use React",
      "I will back or whoever tells me first",
      "I think you'll find that powers don't include conjuring",
      "“don’t break the This is an ambitious goal",
      "Excited to announce that I'll be representing on TC39, the committee",
      "Like, I'm supposedly the 142nd biggest JS-er in I don't even",
      "We need to guarantee that the JS event loop will run at 60 FPS which is impossible",
      "tools in JavaScript has been long and Everyone is constantly reimplementing the same things and it’s created an absolute",
      "Those who disable Javascript",
      "The human mind cannot comprehend JS",
      "JS is sooooo much better bytecode than a real bytecode",
      "bytecode, people -- y'all keep asking for it",
      "I'm obviously way behind the times here, what the heck have they done to Javascript?!",
      "the DOM is slow, but not a lot",
      "almost lamenting ES6's missed chance",
      "my code comes out perfect the first time I write it",
      "I'm pretty sure you could write this in <100 lines of JavaScript, the lack of a \"coherent and strong type system\" notwithstanding",
      "I will have to fix bugs in it, improve it further, make it work together with the rest of the code, defend its And I don’t want to",
      "Oh, wow, thank you V8, good bye",
      "it’s pretty safe to assume JavaScript will just",
      "is JavaScript hard? Consider the following",
      "Tweet I'm a",
      "Underscore has shipped! Unfortunately",
      "can be nice not to",
      "another framework people",
      "In theory Riot is super fast",
      "JavaScript for it's weirdness",
      "I would die for JQuery",
      "about I'm not super informed so I might be wrong, feel free to correct me :)",
      "is not It's",
      "writing JavaScript, I'm considerably less grumpy now",
      "caching, don’t use it",
      "woke up this morning to find that jquery recommends using me for all plugins",
      "whenever I look at WebPack I'm all like … yeah",
      "back here writing jQuery plugins",
      "It's all about React now, grandpa",
      "the Let's free it! No more DOM!",
      "Before the Definitive Guide, before the Good Parts, this was my JavaScript",
      "jsdom needs a big warning at the top of the page",
      "get involved in You'll find yourself",
      "I have about 6 years of experience with This does not seem reasonable to me at",
      "lol Java you wish",
      "If I had a penny for every time JavaScript gets blamed",
      "Here's the thing, I do know Javascript pretty well",
      "“normal” JS code",
      "I guess JS is fun if you're the sort of person who likes having to",
      "Perhaps the regrettable schism brings the “selling",
      "dystopian ember future",
      "not compatible with existing ecosystem",
      "even WebGL requires a bit of DOM",
      "post \"monomorphic javascript",
      "mobile Main problem is can't use",
      "mutters something about",
      "I love But I don't",
      "jQuery? I wasn't aware that jQuery was",
      "npm install hitler",
      "this could be done entirely in I don't really care how",
      "a whole conference just for",
      "Nodejitsu: it has been",
      "enterprise apps are just Now imagine the same app rewritten in JavaScript, with 100x",
      "is the best thing to ever happen",
      "with We are eager to put this all behind us but we can’t",
      "To be fair the JVM is really fast",
      "Browsing with Firefox is no longer supported on Android",
      "lodash was too hefty",
      "can't buy decent :(",
      "I'm not part of the \"real\" Javascript community, and have decided: fuck",
      "Augh, domains are",
      "jQuery?",
      "makes the world much slower",
      "weird about ember",
      "JS A BUTT",
      "a JavaScript runtime on Am I missing something?",
      "fun happy JS spirit-ball rolling around",
      "Many users would say that it has been production-ready for quite some time Possibly",
      "wants to join my You should",
      "I'd like to meet these JavaScript types people, I suspect",
      "all those fancy dropdowns, it's harder than you think!",
      "TypeScript isn't real",
      "if you need fast JavaScript for everything",
      "I have very mixed feelings about SoundScript",
      "is writing statically-typed js possible now?  also i wouldn't",
      "what’s that?” asked Joyent CEO Scott Hammond",
      "use the IE8",
      "def attending SF this evening just sayin!",
      "ClojureScript REPL, why would anyone need that?",
      "Ecma: when you care enough to lose",
      "replace IE with",
      "No semicolons It's totally Really!",
      "I’ve polyfilled a thing or two",
      "functions is a big deal™",
      "it's the most elegant JS I've ever written",
      "I npm-installed some JS and used it",
      "It immediately makes sense and is actually somewhat correct!",
      "Yeah, Whoops!",
      "What? There's a",
      "javascript finally *clicked* for me i think",
      "everybody reacts quite viscerally to JSX",
      "I had a mixin that persisted",
      "FFS, ADULT web devs shouldn’t need MIDDLE SCHOOL MATH",
      "code that is as close to the ES3 metal as possible",
      "I DON’T POLYFILL OR COMPILE",
      "what might be difficult to come to terms with is that many of the latest JavaScript tools (for example, Angular are not exactly tested",
      "project stewardship and Boring",
      "Not valid in",
      "For god sakes can people please use parenthesis",
      "jQuery - for example",
      "You think that Javascript is a means to an end glwt",
      "don't build w/",
      "what's more useful than a +1 on an issue",
      "OO programming in Javascript” // glad this is only a joke",
      "Stop it with this ASI Semicolons are cool",
      "asking why Microsoft didn't go for Webkit as the rendering engine",
      "My conclusion from all this: I hope never to render anything server-side ever again",
      "In conclusion: Server rendering is great, use it",
      "anything jQuery does to the DOM, can be done with JS",
      "JSX is a lot",
      "You may be shocked to learn that minified code runs faster in Node than non-minified code",
      "I like iojs ;)",
      "Yes, subtweeting right But its",
      "the JS illuminati want us to believe",
      "Yo what is the react",
      "disappointed in the embracing of OO programming in Javascript",
      "a replacement to support Mootools But why?",
      "the last six years, I've become better",
      "Submit",
      "incompatibilities across browsers? Or have they finally been fixed?",
      "Spartan is the browser we expect",
      "is 019 not a JavaScript syntax error?",
      "NO ONE CARES ABOUT THE EMBER",
      "Hey, I heard Javascript was made in 10 this is an experiment",
      "React is 24x",
      "navigate the salt marsh that is AngularJS",
      "are you looking to get out of the",
      "That’s Netscape released in December of 1994, running inside Windows released in August of 1993, running inside of Google Chrome",
      "this whole business?",
      "the javascript world is an emotional roller coaster",
      "GWT as a JS maybe it's time",
      "frameworks and tooling! What happened to writing JS",
      "Ember went too far",
      "I simply can't read \"minimalistic\" \"modular\" \"lightweight\" anymore without thinking",
      "a wild idea: maybe performance is not a number",
      "Ember computed properties don't work",
      "is so freaking big & complex",
      "Have you ever tried to bind a click event to two buttons? It's like 600 lines of",
      "Writing code is more fun when you can care more",
      "wish npm let us use a modules directory",
      "people will probably still call it ES6",
      "\"HTML5\" or \"CSS3\" are a The same is true for ES 2015, or ES 2016",
      "going to publish my (serious) JS book",
      "there were programmers before JavaScript?!",
      "what do you mean by Markova chain?",
      "reason for teaching JavaScript is that Python sucks",
      "we should question our “objective” and “technical” opinions about programming We should make a point of being open",
      "Microsoft: “We’re making a new browser!” Me: “Oh",
      "you recommend using something different than JavaScript when writing CPU heavy apps? I was under the impression that it's better suited",
      "if you try to go to the npm page, it won't work",
      "If I wanted to develop a web app that only worked in Chrome, it would",
      "Web only works in Google browsers coming",
      "I may be thick, but what does isomorphic mean",
      "Controversial opinion: JavaScript",
      "demanding a js-only world",
      "People are now forking node",
      "Internet Explorer were 1st IE has actually been doing this for some time",
      "if was at tonight, they/he might say something",
      "the npm police they live",
      "realize how terrible I am at JavaScript",
      "just Cue the onslaught of \"when will this work",
      "before React, ¯\_(ツ)_/¯",
      "are Web Components and isomorphic rendering in conflict?",
      "using good JS principles is refreshing",
      "here's a JavaScript cross-compiler I can get behind:",
      "Angular is not jQuery, and it could be",
      "whether you use or you may experience performance",
      "there is no real",
      "with only 10 lines of JavaScript",
      "you want to parse the AST (abstract source tree) and create a static analysis",
      "How many cats worth of complexity are you rendering in your pages?",
      "overwrite a shit ton of stuff on native prototypes",
      "and streams, I do not like",
      "I don't use promises, I don't"
]