module.exports = [
"Fuck the politically minded, here's something I want to say,",
"About the state of nation, the way it treats us today.",
"At school they give you shit, drop you in the pit,",
"You try, you try, you try to get out, but you can't because they've fucked you about.",
"Then you're a prime example of how they must not be,",
"This is just a sample of what they've done to you and me.",
"Do they owe us a living?",
"Of course they do, of course they do.",
"Owe us a living?",
"Of course they do, of course they do.",
"Owe us a living?",
"OF COURSE THEY FUCKING DO.",
"Don't want me anymore, cos I threw it on the floor.",
"Used to call me sweet thing, I'm nobody's plaything,",
"And now that I am different, 'd love to bust my head,",
"You'd love to see me cop-out, 'd love to see me dead.",
"Do they owe us a living?",
"Of course they do, of course they do.",
"Owe us a living?",
"Of course they do, of course they do.",
"Owe us a living?",
"OF COURSE THEY FUCKING DO.",
"The living that is owed to me I'm never going to get,",
"They've buggered this old world up, up to their necks in dept.",
"They'd give you a lobotomy for something you ain't done,",
"They'll make you an epitomy of everything that's wrong.",
"Do they owe us a living?",
"Of course they do, of course they do.",
"Owe us a living?",
"Of course they do, of course they do.",
"Owe us a living?",
"OF COURSE THEY FUCKING DO.",
"Don't take any notice of what the public think,",
"They're so hyped up with T.V., they just don't want to think.",
"They'll use you as a target for demands and for advice,",
"When you don't want to hear it they'll say you're full of vice.",
"Do they owe us a living?",
"Of course they do, of course they do.",
"Owe us a living?",
"Of course they do, of course they do.",
"Owe us a living?",
"OF COURSE THEY FUCKING DO.",
"ATTENTION. Fuck American power. Fuck Russian power. Fuck British power.",
"Fuck all power.",
"ATTENTION. These ignorant shits arm themselves for annihilation and call it world peace.",
"Bollocks.",
"Pacified. Classified.",
"Keep in line. You're doing fine.",
"Lost your voice? There ain't no choice.",
"Play the game. Silent and tame.",
"Be the passive observer, sit back and look",
"At the world they destroyed and the peace that they took.",
"Ask no questions, hear no lies",
"And you'll be living in the comfort of a fool's paradise.",
"You're already dead, you're already dead,",
"You're already dead, you're already dead.",
"If you're the passive observer, here's a message for you...",
"You're already dead, You're already dead.",
"Afraid to do what you know you should do...",
"You're already dead, You're already dead.",
"The world's at the edge of nuclear destruction,",
"But your too afraid to make the connection.",
"You still believe the system's there for your protection...",
"You're already dead, You're already dead.",
"You're already dead, you're already dead,",
"You're already dead, you're already dead.",
"By letting it happen without a fight...",
"You're already dead, You're already dead.",
"With your endless debates about wrong and right...",
"You're already dead, You're already dead.",
"Nothing's going to change if you're not prepared to act,",
"There's no point complaining after the fact,",
"Content to be a number, branded X and neatly packed...",
"You're already dead, You're already dead.",
"You're already dead, You're already dead,",
"You're already dead, You're already dead.",
"Four hundred thousand people marched for CND...",
"They're already dead, They're already dead,",
"Unless they're willing to act on what they can see...",
"They're already dead, They're already dead.",
"If each and every one of us was prepared to fight for more,",
"To stand against the system that creates the need for war,",
"The elite would have to run like it's never run before...",
"They're already dead, They're already dead.",
"They're already dead, They're already dead,",
"They're already dead, They're already dead.",
"We don't need organising",
"Or politicians being patronising.",
"We don't need their leadership,",
"Trendy lefties being hip.",
"Don't need their condescension",
"Or their back to root pretension.",
"We've heard it all before,",
"Politicians saying No more war,",
"Pulling wool across our eyes.",
"We don't need their dangerous lies.",
"We won't accept capitulation,",
"It's just manipulation.",
"They want the smooth without the rough,",
"But words and gestures aren't enough.",
"We've got to learn to reject all leaders",
"And the passive shit they feed us...",
"They're already dead, They're already dead,",
"They're already dead, They're already dead.",
"If you think moderation's going to pave the way to peace...",
"You're already dead, You're already dead.",
"What good is moderation 'gainst the army and police?",
"You're already dead, You're already dead.",
"We're not promoting mindless violence, keep that for the fools,",
"We're simply saying be prepared to break their laws and rules,",
"Let them know the bigger they come, the harder they will fall...",
"They're already dead, They're already dead.",
"They're already dead, They're already dead,",
"They're already dead, They're already dead.",
"If they're going to play it dirty, so are we...",
"They're already dead, They're already dead.",
"They can keep their lies about the land of the free...",
"They're already dead, They're already dead.",
"We've allowed them too often to use their iron fist,",
"But there's one little detail they appear to have missed...",
"You don't have to be PASSIVE just because you're a PACIFIST...",
"They're already dead, They're already dead.",
"They're already dead, They're already dead,",
"They're already dead, They're already dead.",
"They'll try to sell their system",
"Like it's some kind od age-old wisdom,",
"But we've been had like that before,",
"It's just the rich exploiting the poor.",
"Well here's an honest confession,",
"We think it's time they learnt a lesson.",
"They've tried to hold the people down,",
"But we've simply gone underground,",
"Moving in the darkness looking for the light,",
"Looking for a future and ready to fight.",
"Looking for the freedom that's been denied,",
"Fast to attack and fast to hide.",
"In a world where the people can't make it,",
"They've simply got to learn to break it,",
"And if the wealthy aren't prepared to shake it...",
"O.K., we'll simply have to take it...",
"You're already dead, You're already dead,",
"You're already dead, You're already dead,",
"You're already dead, You're already dead,",
"You're already dead, You're already dead...",
"The door stands open -",
"Across lines, invisible hands are held, golden streamers building in the night.",
"Alone, the possibilities are enormous.",
"Step outside and parasites, deprived of their meat, wait to suck on tiring flesh,",
"Unending statistics that fatten leaders, prisoners of their morality.",
"Afraid of death, we can not save ourselves.",
"To breathe is not enough.",
"Yes sir, I Will.",
"When you woke this morning you looked so rocky-eyed,",
"Blue and white normally, but strange ringed like that in black.",
"It doesn't get much better, your voice can get just ripped up shouting in vain,",
"Maybe someone hears what you say, but you're still on your own at night.",
"You've got to make such a noise to understand the silence,",
"Screaming like a jackass, ringing ears so you can't hear the silence",
"Even when it's there. Like the wind seen from the window,",
"Seeing it but not being touched by it.",
"Words sometimes don't seem to mean much;",
"Of anyone we've used more that most.",
"Feelings from the heart that have been distorted and mocked,",
"Thrown around in the spectacle, the grand social circus.",
"Up against the rows of grey robots who control our lives",
"The things we have to offer sometimes seem so frail.",
"As they plan destruction and gain respectability,",
"We offer our creativity and are made outcasts.",
"We didn't expect to find ourselves playing this part,",
"We were concerned with ideas, not rock and roll,",
"But we can't avoid that arena,",
"It's become a part of us even if we don't understand it.",
"In attempts to moderate they ask why we don't write love songs.",
"What is it that we sing then?",
"Our love of life is total, everything we do is an expression of that,",
"Everything that we write is a love song.",
"We look for alternatives,",
"But the enormous power of the media makes it so difficult",
"To establish foundations. Their lies and distortions are so extreme",
"That everything becomes poisoned and corrupted.",
"We can become media personalities, but it is always on their terms.",
"We're tired of living up to other people's expectations when our own are so much higher.",
"Intelligence seems so easily dismissed when it doesn't conform to mainstream values.",
"Lennon said They hate you if you're clever and they despise a fool,",
"He was right. Social intelligence merely requires agreement and compromise.",
"The boundaries are becoming narrower as the State becomes more paranoid.",
"Under authoritarian rule, conformity becomes the only security.",
"Fear is a powerful weapon against human development.",
"Cowering in our temples of self there's little chance of change;",
"The State is aware of that. The bomb serves many functions.",
"If fear of the omnipotent God is no more,",
"The nuclear Father will govern with his shepherd's crook,",
"Drawing his flock closer to the valley of the shadow of death.",
"Those of us who stand out against the status quo",
"Do so against all odds.",
"We cling so closely together",
"Because we have little other than ourselves.",
"Critics say that it's just punk rock or that we're just naive anarchists.",
"They hope to discredit us with their labels and definitions.",
"Throughout history societies have condemned those who are later celebrated as heroes,",
"In so many bourgeois homes Van Gogh's sunflowers radiate from the walls,",
"Yet he lived in utter misery, condemned by those very same people.",
"Why is it that the kind and gentle are subjected to violence and riducule?",
"How is it that the small and mealy-minded have gained so much power?",
"What perversion has taken place that we are governed by fools?",
"We've had problems from self-appointed Gods from Bishops to MPs.",
"They've tried to ban our records saying that we're a threat to decent society.",
"Fuck them. I hope we are.",
"What kind of depraved idiot thinks they can silence others by denying them their voice?",
"For fucks sake, who are these lobotomists?",
"As if walls only had one side.",
"Whispered intimacies might not get through,",
"But cries of anguish know no barriers.",
"But how long do we shout for?",
"Denied the airwaves, we trust in the wind to carry what we say.",
"But sometimes we've found ourselves shouting into the wind",
"When we should have been confiding in each other.",
"It seems so absurd that we are denied the chance of ever being truly free.",
"The terrible inequalities of the peoples of this earth",
"Make freedom at best a dream, at worst an insulting privilege.",
"What space is there for self-expression and personal development",
"When over half the world's population is starving?",
"There are so many things that might have been done,",
"But rooted on this spot in the desire to find solution,",
"There's little to see and feel but the sighing and dying of our world.",
"But for suffering we might have been a part of it rather than apart from it.",
"Making the compromises,",
"Brave fronts, deceitful disguises. What did you know? What did you care?",
"What did you know? What did you care?",
"Turning a blind eye to the lies just to keep it all together,",
"But sometimes when I'm alone like this I wonder whether it's worth it.",
"Smiling and socialising.",
"Endless philosophising. What did you know? What did you care?",
"What did you know? What did you care?",
"Surface agreements, statements of fact, trying to prove we can do it,",
"But sometimes when I'm alone like this I wonder just who can see through it.",
"Bargains and sacrifices.",
"Cheap tricks, cheaper devices. What did you know? What did you care?",
"What did you know? What did you care?",
"Holding the vision, but losing our sight, endlessly searching solution,",
"But sometimes when I'm alone like this I wonder how much it's just institution.",
"What did you know? What did you care?",
"What did you know? What did you care?",
"What did you know? What did you care?",
"What did you know? What did you care?",
"Anarchy's become another word for 'got 10p to spare?' What did you know? What did you care?",
"Another way of saying 'I'm O.K., sod you out there'. What did you know? What did you care?",
"Another token tantrum to cover up the fear. What did you know? What did you care?",
"Another institution, another cross to bear. What did you know? What did you care?",
"etc. etc.",
"Anything and everything can be so easily institutionalised,",
"A poor parody of itself. Itself contained by itself.",
"There's no point in just mouthing the words.",
"The token tantrums just aren't enough,",
"Nor is speed and weed and the Positive Creed.",
"Exclusive clubs where the various tribes congratulate each other for doing fuck all",
"Will achieve nothing but the strengthening of the status quo.",
"Punk has spawned another rock and roll elite,",
"Cheap Rotten Vicious imitations thinking they'll change their world",
"With dyed hair and predictable gestures. Nouveau wankers.",
"There's a thousand empty stages waiting for their empty performances,",
"A thousand empty faces waiting for their empty stances.",
"How many times must we hear rehashed versions of Feeding of the 5000",
"By jerks whose only fuck off to the system has been one off the wrist?",
"It's the Feeding of the 5 Knuckle Shuffle.",
"If there was no government, wouldn't there be chaos",
"Everybody running round, setting petrol bombs off?",
"And if there was no police force, tell me what you'd do",
"If thirty thousand rioters came running after you?",
"And who would clean the sewers? Who'd mend my television?",
"Wouldn't people lay about without some supervision?",
"Who'd drive the fire engines? Who'd fix my video?",
"If there were no prisons, well, where would robbers go?",
"And what if I told you to Fxxk Off?",
"What if there's no army to stop a big invasion?",
"Who'd clean the bogs and sweep the floors? We'd have all immigration.",
"Who'd pull the pint at the local pub? Where'd I get my fags?",
"Who'd empty out my dustbins? Would I still get plastic bags?",
"If there were no hospitals, and no doctors too,",
"If I'd broken both my legs, where would I run to?",
"If there's no medication, if there were no nurses,",
"Wouldn't people die a lot? And who would drive the hearses?",
"And what if I told you to Fxxk Off?",
"If there were no butchers shops, what would people eat?",
"You'd have everybody starving if they didn't get their meat.",
"If there was no water, what would people drink?",
"Who'd flush away the you-know-what? But of course MINE never stink.",
"What about the children? Who'd teach them in the schools?",
"Who'd make the beggers keep in line? Learn them all the rules?",
"Who's tell us whitewash windows? When to take down doors?",
"Tell us make a flask of tea and survive the holocaust?",
"The rock and roll swindler says it's O.K. to plunder,",
"So the pirates set sail to rape any ethnic culture they can plug a mike to.",
"The imperialists rub their hands in glee",
"As the slave-boy hunts out butt-ends in the garbage cans.",
"Is it any wonder there was such sickening celebration over the Task Force",
"When so called radicals work hand in hand with the ruling elite?",
"Yesterday those wily creeps rejected the status quo,",
"Today they smarm and charm passageways to its very heart.",
"Where's the free individual in all that?",
"Where's the hope and aspiration?",
"Identities have become corporations,",
"Social egos and media moulds,",
"Scholars of ad-man's dreams. Prescribed futures;",
"Must we all down aspirins and shine beneath borrowed tans?",
"Are we really so dumb, so cowered into submission",
"That not only are we prepared to eat shit",
"We're also prepared to say thanks for the privilege?",
"Why should we accept servility as a bargain for dignity?",
"Why should we passively accept death as a bargain for living?",
"Why accept this robbery of life? Why accept this pillage?",
"For Christ's sake take up your bed and walk.",
"Let the blind see end the deaf hear.",
"The rights of the individual are dependent upon",
"You realising your right as an individual.",
"People are so easily deluded into thinking they've instrumented choice",
"Where in reality they're nothing but passive observers.",
"Passive observers do nothing but passively observe,",
"Passively soak up creativity and say Wow, that's me!,",
"Passively soak up destruction and say Oh no, not us, not me.",
"There are those who strive for value and meaning;",
"Who search for reason and purpose;",
"Their efforts are negated by the passive observers."
]